<template>
  <div id="js_article" class="rich_media preview_appmsg">
    <div id="js_top_ad_area" class="top_banner" style="display: none;"></div>
    <div class="rich_media_inner">
      <div id="page-content" class="rich_media_area_primary">
        <div id="img-content">
          <h2 class="rich_media_title" id="activity-name"> 儿童天赋基因检测</h2>
          <div id="meta_content" class="rich_media_meta_list">
            <em id="post-date" class="rich_media_meta rich_media_meta_text">2017-08-11</em>
            <em class="rich_media_meta rich_media_meta_text">华晟医学</em>
            </div>
          </div>
          <div class="rich_media_content " id="js_content">
            <p style="font-family: 微软雅黑;">
              <img src="static/img/adv//banner3.png" style="width: 100% !important; height: 130px; !important; visibility: visible !important;" data-fail="0"></p><section class="" data-tools="135编辑器" data-id="86516" style="font-family: 微软雅黑; border: 0px none; box-sizing: border-box;"><section style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(221, 221, 221); margin-right: auto; margin-bottom: 10px; margin-left: auto; box-sizing: border-box;">
            <p class="" data-brushtype="text" style="padding-right: 5px; padding-bottom: 6px; padding-left: 5px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(239, 112, 96); display: inline-block; margin-bottom: -1px; line-height: 1.1; font-size: 18px;"><span style="font-family: 站酷高端黑; font-size: 16px;">☀<span style="line-height: inherit; font-size:16px">儿童天赋基因检测</span></span>&nbsp;</p></section></section><section class="" data-tools="135编辑器" data-id="90202" style="font-family: 微软雅黑; border: 0px none; box-sizing: border-box;"><section style="padding: 10px 15px; box-sizing: border-box;">
            <section style="width:100%;" data-width="100%">
              <img style="margin-left: -5px; width: auto !important; height: auto !important; visibility: visible !important;" data-src="" class="" data-ratio="0.5842696629213483" data-w="89" data-type="png" src="static/img/adv//bgRedTitle.png" data-fail="0"></section><section style="width:100%; margin-top:-40px; font-size:16px; color:#fff;" data-width="100%"><section style="display:inline-block; margin-left:5px;">part 1</section></section>
            <section style="padding: 20px 25px; box-shadow: rgb(204, 204, 204) 0px 0px 5px; margin-top: -37px; box-sizing: border-box;">
              <section style="width:100%; font-size:14px; font-weight:bold; text-align:center;" class="" data-brushtype="text" data-width="100%"><p class=""> <span class="">宝宝天赋能力早知道</span></p>
              </section><section style="width:100%; font-size:14px;margin-top: 10px;" class="" data-width="100%">
              <p><span style="font-family: 站酷高端黑;">儿童天赋基因检测是华晟医学采用国际领先的基因检测技术，结合中国儿童基因库大数据研发出适合中国儿童的天赋基因检测产品。俗话说，父母是孩子最好的老师，如果父母了解孩子与生俱来的优势基因，进而因材施教，让孩子在自己最擅长的领域学习成长，才是最佳的培养方式。</span></p></section></section><section style="width:100%; text-align:right; margin-top:-20px;" data-width="100%"><img data-src="" class="" data-ratio="0.84" data-w="25" data-type="png" src="static/img/adv//bgRed.png" style="width: auto !important; height: auto !important; visibility: visible !important;" data-fail="0"></section></section></section>
            <p style="font-family: 微软雅黑; text-align: center;"><span style="font-family: 站酷高端黑;">TESTING</span></p>
            <p style="text-align: center;">
              <span style="font-family:站酷高端黑">我们检测</span></p><p style="text-align:center">
            <span style="font-size: 14px; font-family: 站酷高端黑;">从25000个基因、30亿个碱基对中寻找孩子的天赋潜能，超精准技术平台分析，出具权威检测报告，为孩子的培养提供新的指导方向。</span></p><section class="" data-tools="135编辑器" data-id="90143" style="border: 0px none; box-sizing: border-box;" data-color="rgb(216, 40, 33)" data-custom="rgb(216, 40, 33)"><section style="text-align:center;"><section style="display: inline-block; vertical-align: middle; padding-right: 3px; box-sizing: border-box;"><section style="border-top-width: 3px; border-top-style: solid; border-top-color: transparent; border-left-width: 3px; border-left-style: solid; border-left-color: rgb(102, 102, 102); float: right; box-sizing: border-box;"></section>
            <section style="color: rgb(255, 255, 255); font-size: 1em; margin-right: 3px; padding: 0.5em; background: rgb(216, 40, 33);transform: rotate(360deg);-webkit-transform: rotate(360deg);-moz-transform: rotate(360deg);-ms-transform: rotate(360deg);-o-transform: rotate(360deg);">
              <p class="" data-original-title="" title="">1</p>
            </section>
            <section style="border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: transparent; border-left-width: 3px; border-left-style: solid; border-left-color: rgb(102, 102, 102); margin-top: -3px; float: right; box-sizing: border-box;">

            </section></section><section style="display: inline-block; vertical-align: middle; margin-left: -3em; font-size: 0.875em; line-height: 1.5; padding: 0.5em 1em 0.5em 3em; box-sizing: border-box; background: rgb(238, 238, 238);"><p class="" data-brushtype="text">五大天赋</p></section></section></section><p style="text-align: center;"><span style="font-size: 14px; font-family: 站酷高端黑;">❖ 运动天赋 &nbsp; &nbsp; ❖ 学习天赋 &nbsp; &nbsp;❖ 记忆天赋 &nbsp;</span></p><p style="text-align: center;"><span style="font-family: 站酷高端黑; font-size: 14px;">❖ 记忆天赋 &nbsp;</span>&nbsp; &nbsp; <span style="font-size: 14px; font-family: 站酷高端黑;">❖ 音乐天赋 &nbsp;</span>&nbsp;</p><section class="" data-tools="135编辑器" data-id="90143" style="border: 0px none; box-sizing: border-box;" data-color="rgb(216, 40, 33)" data-custom="rgb(216, 40, 33)"><section style="text-align:center;"><section style="display: inline-block; vertical-align: middle; padding-right: 3px; box-sizing: border-box;"><section style="border-top-width: 3px; border-top-style: solid; border-top-color: transparent; border-left-width: 3px; border-left-style: solid; border-left-color: rgb(102, 102, 102); float: right; box-sizing: border-box;"></section><section style="color: rgb(255, 255, 255); font-size: 1em; margin-right: 3px; padding: 0.5em; background: rgb(216, 40, 33);transform: rotate(360deg);-webkit-transform: rotate(360deg);-moz-transform: rotate(360deg);-ms-transform: rotate(360deg);-o-transform: rotate(360deg);"><p class="" data-original-title="" title="">2</p></section><section style="border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: transparent; border-left-width: 3px; border-left-style: solid; border-left-color: rgb(102, 102, 102); margin-top: -3px; float: right; box-sizing: border-box;"></section></section><section style="display: inline-block; vertical-align: middle; margin-left: -3em; font-size: 0.875em; line-height: 1.5; padding: 0.5em 1em 0.5em 3em; box-sizing: border-box; background: rgb(238, 238, 238);"><p class="" data-brushtype="text">三大能力</p></section></section></section><section class="" data-tools="135编辑器" data-id="85862" style="border: 0px none; box-sizing: border-box;"><section style="text-align: center;width: 99%;" data-width="99%"><section style="width: 33%; display: inline-block;box-sizing:border-box; padding: 0.5em;" class="" data-width="33%">
            <section data-role="circle" style="border-radius: 100%; overflow: hidden; margin-right: auto; margin-left: auto; width: 100%; padding-bottom: 100%; height: 0px; box-sizing: border-box; background-image: url('static/img/adv//p3_02.png'); background-size: cover; background-position: 50% 50%;" data-width="100%">
            <img data-src="static/img/adv//p3_02.png" style="opacity: 0; width: auto !important; height: auto !important; visibility: visible !important;" title="专注力天赋.png" class="" data-ratio="1" data-w="140" data-type="png" src="static/img/adv//p3_02.png" data-fail="0"></section><section><p style="font-size: 14px; text-decoration: inherit;"><span style="color: rgb(89, 89, 89); font-family: 站酷高端黑; font-size: 12px;">专注力天赋</span></p></section></section><section style="width: 33%;box-sizing:border-box; padding: 0.5em; display: inline-block;" class="" data-width="33%"><section data-role="circle" style="border-radius: 100%; overflow: hidden; margin-right: auto; margin-left: auto; width: 100%; padding-bottom: 100%; height: 0px; box-sizing: border-box; background-image: url(static/img/adv//p3_03.png); background-size: cover; background-position: 50% 50%;" data-width="100%">
            <img data-src="static/img/adv//p3_03.png" style="opacity: 0; width: auto !important; height: auto !important; visibility: visible !important;" title="领导力天赋.png" class="" data-ratio="1" data-w="140" data-type="png" src="static/img/adv//p3_03.png" data-fail="0"></section><section><p style="font-size: 14px; text-decoration: inherit;"><span style="color: rgb(89, 89, 89); font-family: 站酷高端黑; font-size: 12px;">领导力天赋</span></p></section></section><section style="width: 33%; box-sizing:border-box;padding: 0.5em; display: inline-block;" class="" data-width="33%"><section data-role="circle" style="border-radius: 100%; overflow: hidden; margin-right: auto; margin-left: auto; width: 100%; padding-bottom: 100%; height: 0px; box-sizing: border-box; background-image: url('static/img/adv//p3_04.png'); background-size: cover; background-position: 50% 50%;" data-width="100%">
            <img data-src="static/img/adv//p3_04.png" style="opacity: 0; width: auto !important; height: auto !important; visibility: visible !important;" title="执行力天赋.png" class="" data-ratio="1" data-w="140" data-type="png" src="static/img/adv//p3_04.png" data-fail="0"></section><section><p style="font-size: 14px; text-decoration: inherit;"><span style="color: rgb(89, 89, 89); font-family: 站酷高端黑; font-size: 12px;">执行力天赋</span></p></section></section></section></section><p style="font-family: 微软雅黑; text-align: center;">ADVANTAGE<br></p><p style="text-align: center;"><span style="font-family:站酷高端黑">检测优势</span></p><p style="line-height:150%"><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑; color: rgb(192, 0, 0);">权威平台：</span><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑;">由生物芯片上海国家工程研究中心检测，并出具权威报告；</span></p><p style="line-height:150%"><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑; color: rgb(192, 0, 0);">科学认证：</span><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑;">源于人体机能原理分析，经多国科学家临床科研验证，结果科学可靠；</span></p><p style="line-height:150%"><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑; color: rgb(192, 0, 0);">专业解读：</span><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑;">权威细致的报告解读，渗透基因对天赋的影响机理，制定符合孩子的个性化培养方案；</span></p><p style="line-height:150%"><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑; color: rgb(192, 0, 0);">取样便捷：</span><span style="line-height: 150%; font-size: 14px; font-family: 站酷高端黑;">采用口腔黏膜样本检测，采样简单、无痛；</span></p><section class="" data-tools="135编辑器" data-id="86412" style="border: 0px none; box-sizing: border-box;"><section style="margin: 1em auto; border: none; text-align: center; box-sizing: border-box;"><section style="border-left-width: 3px; border-left-style: solid; border-left-color: rgb(170, 166, 149); box-sizing: border-box;"><section class="" style="margin-left: 2px; padding: 0.6em; line-height: 1.5; text-align: left; border-left-style: solid; border-left-width: 1px; border-color: rgb(170, 166, 149); box-sizing: border-box;"><p class=""><span style="font-family: 站酷高端黑; font-size: 14px;">中国式的家庭教育，60%以上的家长培养孩子是失败的！导致这一现状的根本原因是没弄清孩子的遗传天赋，一厢情愿地按照大人的心愿去培养，进行教育投资，最后，花费了 的财力和精</span><span style="font-family: 站酷高端黑; font-size: 14px; line-height: 1.5;">力却收效甚微，甚至造成培养失败，然而最大的损失是埋没了孩子的天赋。</span></p><p class=""><span style="font-family: 站酷高端黑; font-size: 14px; line-height: 1.5;"><br></span></p><p class=""><span style="font-family: 站酷高端黑; font-size: 14px; line-height: 1.5;">因此对孩子进行培养时一定要考虑遗传天赋，避免误判天赋，做到因材施教。</span></p></section></section></section></section>
          </div>
        </div>
      </div>
    </div>
</template>
<style>
body.rich_media_empty_extra .rich_media_area_primary:before{display:none}
.rich_media_inner{font-size:16px;word-wrap:break-word;-webkit-hyphens:auto;-ms-hyphens:auto;hyphens:auto}
.rich_media_area_primary{position:relative;padding:0 15px 15px 20px;background-color:#fff}
.rich_media_area_primary:before{content:" ";position:absolute;left:0;top:0;width:100%;height:1px;
  border-top:1px solid #e5e5e5;-webkit-transform-origin:0 0;transform-origin:0 0;-webkit-transform:scaleY(0.5);transform:scaleY(0.5);top:auto;bottom:-2px}
.rich_media_title{margin-bottom:10px;line-height:1.4;font-weight:400;font-size:24px}
.rich_media_meta_list{margin-bottom:18px;line-height:20px;font-size:0}
.rich_media_meta_list em{font-style:normal}
.rich_media_meta{display:inline-block;vertical-align:middle;margin-right:8px;margin-bottom:10px;font-size:16px}</style>
